# Generated by Django 4.2.3 on 2025-01-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Пример: +7 (123) 123-12-12', max_length=40, null=True, verbose_name='Телефон')),
                ('wa', models.CharField(blank=True, help_text='Пример: 71231231212', max_length=40, null=True, verbose_name='WhatsApp')),
                ('tg', models.CharField(blank=True, help_text='Пример: nickname', max_length=40, null=True, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, help_text='Пример: zakaz@pskovshevron.ru', max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
