# Generated by Django 4.2.3 on 2025-01-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='SiteSettingsModel',
        ),
    ]
