# Generated by Django 4.2.3 on 2025-01-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_sitesettings_sitesettingsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettingsModel',
            new_name='ContactsModel',
        ),
        migrations.AlterModelOptions(
            name='contactsmodel',
            options={'verbose_name': 'Контактные данные', 'verbose_name_plural': 'Контактные данные'},
        ),
    ]
