# Generated by Django 4.2.3 on 2025-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sitesettingsmodel_contactsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Телефон'),
        ),
    ]
