# Generated by Django 4.2.3 on 2025-01-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactsmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsmodel',
            name='tg',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='contactsmodel',
            name='wa',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Телефон'),
        ),
    ]
